--- # provision ec2 instances
- hosts: local
  become: yes
  gather_facts: no
  connection: local
  remote_user: avinash
  vars_files:
  - ../files/awscreds.yml
  tasks: 
  - name: Provision
    ec2:
        aws_access_key: "{{ aws_key }}"
        aws_secret_key: "{{  aws_secret }}"
        region: ap-south-1
        instance_ids: i-0a44e98a9b578d7dd,i-0b74b540918edc3fc
        state: absent
 
